image: node:22

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - corepack enable
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out  # Next.js place les fichiers statiques dans "out/"
  only:
    - master  # Déploiement depuis la branche "master"

deploy:
  stage: deploy
  script:
    - mv out public  # GitLab Pages sert les fichiers depuis "public/"
  artifacts:
    paths:
      - public
  only:
    - master
